# Generated by Django 3.1.2 on 2020-12-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HjemmeSideInfoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overskrift_1', models.CharField(blank=True, max_length=200, null=True)),
                ('tekst_1', models.TextField(blank=True, max_length=2000, null=True)),
                ('overskrift_2', models.CharField(blank=True, max_length=200, null=True)),
                ('tekst_2', models.TextField(blank=True, max_length=2000, null=True)),
                ('link_til_aktiv_gruppe', models.URLField(max_length=300)),
                ('pris', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
